# Generated by Django 3.2.3 on 2021-06-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id  Categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Libro')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('autor', models.CharField(max_length=40, verbose_name='Autor')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
